name: Test & Release Package

on:
  push:
    tags: 
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tags:

jobs:
  test-build:
    name: Test Package
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  release-build:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Version
        id: version
        run: |
           VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
           echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          name: ${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
